name: Build and Test

on:
  push:
    branches:
    - main
    
jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        platform:
          - iOS
    steps:
      - uses: mxcl/xcodebuild@v1
        with:
          platform: ${{ matrix.platform }}